name=ScreenManager
version=1.0.0
author=Philip Fletcher <philip.fletcher@stutchbury.com>
maintainer=Philip Fletcher <philip.fletcher@stutchbury.com>
sentence=A lightweight C++ library for managing application screens, navigation, transitions and display timing. It is platform, framework and GFX agnostic.
paragraph=ScreenManager is designed for applications composed of multiple screens or views, on embedded systems/microcontrollers. It provides a simple, predictable framework for screen navigation without depending on any graphics, widget or input library.
category=Display
includes=ScreenManager.h
url=https://github.com/Stutchbury/ScreenManager
architectures=*
